language: fortran

sudo: required

env:
  matrix:
    - IFMPI=false F77=gfortran CC=gcc TEST_CASE=Eddy_EddyUv::test_PnPn_Serial
    - IFMPI=false F77=gfortran CC=gcc TEST_CASE=Eddy_EddyUv::test_PnPn2_Serial

    - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=Axi::test_PnPn_Serial
    - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=Axi::test_PnPn_Parallel
    - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=Axi::test_PnPn2_Serial
    - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=Axi::test_PnPn2_Parallel

    - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=Benard_Ray9::test_PnPn_Serial
    - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=Benard_Ray9::test_PnPn2_Serial
    # - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=Benard_RayDD::test_PnPn_Serial   # Exceeds time limit for Travis jobs
    # - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=Benard_RayDD::test_PnPn2_Serial  # Stdout exceeds Travis' max log length
    # - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=Benard_RayDN::test_PnPn_Serial   # Exceeds time limit for Travis jobs
    - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=Benard_RayDN::test_PnPn2_Serial
    # - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=Benard_RayNN::test_PnPn_Serial   # Exceeds time limit for Travis jobs
    # - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=Benard_RayNN::test_PnPn2_Serial  # Exceeds time limit for Travis jobs

    - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=Eddy_EddyUv::test_PnPn_Serial
    - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=Eddy_EddyUv::test_PnPn_Parallel
    - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=Eddy_EddyUv::test_PnPn2_Serial
    - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=Eddy_EddyUv::test_PnPn2_Parallel

    - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=KovStState::test_PnPn2_Serial
    - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=KovStState::test_PnPn2_Parallel

    - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=LowMachTest::test_PnPn_Serial
    - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=LowMachTest::test_PnPn_Parallel
    - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=LowMachTest::test_PnPn2_Serial
    - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=LowMachTest::test_PnPn2_Parallel

    # - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=VarVis::test_PnPn_Serial    # Stdout exceeds Travis' max log length
    # - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=VarVis::test_PnPn_Parallel  # Stdout exceeds Travis' max log length
    # - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=VarVis::test_PnPn2_Serial   # Stdout exceeds Travis' max log length
    # - IFMPI=true F77=mpif77 CC=mpicc TEST_CASE=VarVis::test_PnPn2_Parallel # Stdout exceeds Travis' max log length

before_install: 
  - export ROOT_DIR=`pwd`

  - export SOURCE_ROOT=$ROOT_DIR
  - export EXAMPLES_ROOT=$ROOT_DIR/short_tests
  - export VERBOSE_TESTS=true
  - export PARALLEL_PROCS=2

  - sudo apt-get update -qq
  - sudo apt-get install -y libmpich-dev mpich

  - virtualenv -p python2.7 $ROOT_DIR/python2-env
  - source $ROOT_DIR/python2-env/bin/activate
  - export PYTHONPATH="$ROOT_DIR/short_tests:$PYTHONPATH"
 
install:
  - pip install --upgrade pip
  - pip install pytest

script: 
  - py.test -s -v $ROOT_DIR/short_tests/NekTests.py::$TEST_CASE
